#ifndef SIMPLICITI_COMMON_H
#define SIMPLICITI_COMMON_H

typedef enum
{
    SIMPLICITI_SUCCESS,
    SIMPLICITI_ERROR_INVALID_PARAM,
    SIMPLICITI_ERROR_DECODING,
    SIMPLICITI_ERROR_ENCODING,
} simpliciti_status_t;

#endif // SIMPLICITI_COMMON_H